### ISSUE TITLE
Web Frontend Main Comunity 페이지 Footer 버그발견

### ISSUE THREAD

**Issue by mjkoo711** [kookmin-sw/2018-cap1-1#219]
Web Frontend Main Comunity 페이지 Footer 버그발견

**Comment by dksekfldks65** [comment]
커뮤니티에 글작성하고 들어가면, 깃허브랑 페이스북 링크가 하단 파란색창이 맨밑에 붙어있으면 더좋을꺼 같습니다. 댓글을 작성해야 밑으로 점점 내려갑니다.

**Comment by dksekfldks65** [comment]
논문구독페이지에서 논문 내용 1페이지만 보여주는 기능이 필요합니다. 그리고 논문 구독을 누르고 결제가 된다면 그때서야 논문 전체를 보여줘야합니다.

**Comment by mjkoo711** [comment]
@dksekfldks65 첫번째 것에 대한 내용은 220번 브랜치에서 수정을 완료하였습니다.
@dksekfldks65 두번째 것에 대한 내용은 논문의 1페이지만을 따로 저장하는 DB를 두거나, 혹은 그냥 Abstract만 보여주는 것만 하여야 할것 같습니다.
