### ISSUE TITLE
Web Frontend 추가해야할 것

### ISSUE THREAD

**Issue by achaccha** [kookmin-sw/2018-cap1-1#235]
1. 메인 화면
- 더 알아보기 지우기
- 논문 템플릿 다운로드 받을 수 있게 하기

2. 논문 검수 및 등록 페이지
- 논문 검수 및 등록으로 제목 바꾸기
- 더 알아보기 지우기
- 커뮤니티 형식처럼 번호, 제목, 저자, 버젼, 조회수를 보여주는 것이 어떨까?
- 논문을 클릭하면 번호가 나올 수 있도록

3. 논문 구독 페이지
- 더 알아보기 지우기
- 커뮤니티 형식처럼 번호, 제목, 저자, 가치, 조회수를 보여주는 것이 어떨까?
- 논문을 클릭하면 번호와 가치가 나올 수 있도록

4. 커뮤니티
- 사용자의 명성에 따른 메달 보여주기
- 더 알아보기 클릭하면 명성을 어떤식으로 증가시킬 수 있는지, 얼마의 명성일때 메달이 업그레이드 되는지 설명해주기

5. 토큰 거래하기
- 이더리움을 이더로 바꿀것

**Comment by mjkoo711** [comment]
2번안에 있는 아래 2개는 아직 진행하지 않겠습니다. 나중에 엄형근 형의 수정이 완료되면 다시 진행하겠습니다.

**Comment by mjkoo711** [comment]
4번에 있는 첫번째 것은 사용자의 명성 값을 아직 못받아오기 때문에 보류하겠습니다.
